services:
  - type: web
    name: soulsketchv2-clean
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8080
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENABLE_EMAIL_DELIVERY
        value: true
      - key: ENABLE_ORDER_CONFIRMATIONS
        value: true
      - key: ENABLE_MONITORING_ENDPOINTS
        value: true
      - key: ENABLE_DETAILED_LOGGING
        value: true
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_PATH
        value: ./db/soulmatesketch.sqlite
      - key: UPLOADS_DIR
        value: ./uploads